### ISSUE TITLE
Explore new layouts for blog page

### ISSUE THREAD

**Issue by guytepper** [Gizra/gizra.com#470] opened 2016-07-25 09:04 UTC
![screen shot 2016-07-25 at 11 59 01 am](https://cloud.githubusercontent.com/assets/13344923/17095871/57af466e-525f-11e6-9778-0193497a6a44.png)

This cause of this is [here](https://github.com/Gizra/gizra.com/blob/master/app/_scss/_homepage.scss#L82-L86) - the `height` value shouldn't be `100vh` on that section, I believe.

**Comment by IshaDakota** [comment] 2016-07-25 22:29
@guytepper The vertical height element is by design (so that each section is a full height "slide"), what's missing there is the `display: flex` property that will align the elements vertically.

**Comment by guytepper** [comment] 2016-07-26 05:15
I think that it's better not to make this section full height, it's just not looking good - even with vertical align on:
![image](https://cloud.githubusercontent.com/assets/13344923/17126791/02810182-5309-11e6-8810-b9c1b634e2ca.png)

**Comment by IshaDakota** [comment] 2016-09-08 13:32
@guytepper @RachelBaram we could do either what @DavidKohav suggests in #486 or go back to 3 across, 2 rows (that would require some fidgeting with the teaser cards & titles.

**Comment by RachelBaram** [comment] 2016-09-08 13:53
I like 3 across and am willing to do the title changes.

**Comment by IshaDakota** [comment] 2016-09-08 20:15
I'd prefer try to do it without title changes - I don't think any of the titles are absurdly long and it seems janky to try to fit content into a shape rather than for it to adapt into the space.

Let me open PR and try a few things and we can have a fashion show ;)

regardless, We can make this two rows in the meantime... that's fairly trivial.

**Comment by RachelBaram** [comment] 2016-09-08 20:24
Cool. Looking forward to the fashion show.

**Comment by IshaDakota** [comment] 2016-09-19 21:54
merged and deployed original issue. Leaving open and re-titling for further exploration of blog page layout.

**Comment by IshaDakota** [comment] 2017-02-14 17:33
no longer relevant

**Closed by IshaDakota** 2017-02-14 17:33 UTC
